import sqlite3
from utils.config import DB_PATH
from datetime import datetime, timedelta

def get_connection():
    return sqlite3.connect(DB_PATH, check_same_thread=False)

def init_db():
    conn = get_connection()
    cursor = conn.cursor()

    # Vendor/Equipment Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS Vendor (
        EquipmentID TEXT PRIMARY KEY,
        Type TEXT,
        SiteID INTEGER,
        CheckOutDate TEXT,
        CheckInDate TEXT,
        EngineHourDay REAL,
        IdleHourDay REAL,
        OperatingDays INTEGER,
        DaysLeft INTEGER,
        Fuel REAL,
        Location TEXT,
        Availability TEXT CHECK(Availability IN ('Available', 'Rented')) DEFAULT 'Available',
        RentalType TEXT CHECK(RentalType IN ('Rigid', 'Flexible'))
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS SiteInfo (
        SiteID INTEGER,
        EquipmentID TEXT,
        Location TEXT,
        ContactDetails TEXT,
        FOREIGN KEY (EquipmentID) REFERENCES Vendor(EquipmentID)
    )
    """)

    cursor.execute("SELECT COUNT(*) FROM Vendor")
    count = cursor.fetchone()[0]

    if count == 0:
        equipment_list = [
            
            ('EQX1151', 'Excavator', 'Available'),
            ('EQX1152', 'Excavator', 'Available'),
            ('EQX1153', 'Excavator', 'Available'),
            ('EQX1154', 'Excavator', 'Available'),
            ('EQX1155', 'Excavator', 'Available'),
            ('EQX1156', 'Excavator', 'Available'),
            ('EQX1157', 'Excavator', 'Available'),
            ('EQX1158', 'Excavator', 'Available'),
            ('EQX1159', 'Excavator', 'Available'),
            ('EQX1160', 'Excavator', 'Available'),
            ('EQX1161', 'Excavator', 'Available'),
            ('EQX1162', 'Excavator', 'Available'),
            ('EQX1163', 'Excavator', 'Available'),
            ('EQX1164', 'Excavator', 'Available'),
            ('EQX1165', 'Excavator', 'Available'),
            ('EQX1166', 'Excavator', 'Available'),
            ('EQX1167', 'Excavator', 'Available'),
            ('EQX1168', 'Excavator', 'Available'),
            ('EQX1169', 'Excavator', 'Available'),
            ('EQX1170', 'Excavator', 'Available'),
            ('EQX1171', 'Excavator', 'Available'),
            ('EQX1172', 'Excavator', 'Available'),
            ('EQX1173', 'Excavator', 'Available'),
            ('EQX1174', 'Excavator', 'Available'),
            ('EQX1175', 'Excavator', 'Available'),
            ('EQX1176', 'Excavator', 'Available'),
            ('EQX1177', 'Excavator', 'Available'),
            ('EQX1178', 'Excavator', 'Available'),
            ('EQX1179', 'Excavator', 'Available'),
            ('EQX1180', 'Excavator', 'Available'),
            ('EQX1181', 'Excavator', 'Available'),
            ('EQX1182', 'Excavator', 'Available'),
            ('EQX1183', 'Excavator', 'Available'),
            ('EQX1184', 'Excavator', 'Available'),
            ('EQX1185', 'Excavator', 'Available'),
            ('EQX1186', 'Excavator', 'Available'),
            ('EQX1187', 'Excavator', 'Available'),
            ('EQX1188', 'Excavator', 'Available'),
            ('EQX1189', 'Excavator', 'Available'),
            ('EQX1190', 'Excavator', 'Available'),
            ('EQX1191', 'Excavator', 'Available'),
            ('EQX1192', 'Excavator', 'Available'),
            ('EQX1193', 'Excavator', 'Available'),
            ('EQX1194', 'Excavator', 'Available'),
            ('EQX1195', 'Excavator', 'Available'),
            ('EQX1196', 'Excavator', 'Available'),
            ('EQX1197', 'Excavator', 'Available'),
            ('EQX1198', 'Excavator', 'Available'),
            ('EQX1199', 'Excavator', 'Available'),
            ('EQX1200', 'Excavator', 'Available'),
            ('EQX1201', 'Excavator', 'Available'),
            ('EQX1202', 'Excavator', 'Available'),
            ('EQX1203', 'Excavator', 'Available'),
            ('EQX1204', 'Excavator', 'Available'),
            ('EQX1205', 'Excavator', 'Available'),
            ('EQX1206', 'Excavator', 'Available'),
            ('EQX1207', 'Excavator', 'Available'),
            ('EQX1208', 'Excavator', 'Available'),
            ('EQX1209', 'Excavator', 'Available'),
            ('EQX1210', 'Excavator', 'Available'),
            ('EQX1211', 'Excavator', 'Available'),
            ('EQX1212', 'Excavator', 'Available'),
            ('EQX1213', 'Excavator', 'Available'),
            ('EQX1214', 'Excavator', 'Available'),
            ('EQX1215', 'Excavator', 'Available'),
            ('EQX1216', 'Excavator', 'Available'),
            ('EQX1217', 'Excavator', 'Available'),
            ('EQX1218', 'Excavator', 'Available'),
            ('EQX1219', 'Excavator', 'Available'),
            ('EQX1220', 'Excavator', 'Available'),
            ('EQX1221', 'Excavator', 'Available'),
            ('EQX1222', 'Excavator', 'Available'),
            ('EQX1223', 'Excavator', 'Available'),
            ('EQX1224', 'Excavator', 'Available'),
            ('EQX1225', 'Excavator', 'Available'),
            ('EQX1226', 'Excavator', 'Available'),
            ('EQX1227', 'Excavator', 'Available'),
            ('EQX1228', 'Excavator', 'Available'),
            ('EQX1229', 'Excavator', 'Available'),
            ('EQX1230', 'Excavator', 'Available'),
            ('EQX1231', 'Excavator', 'Available'),
            ('EQX1232', 'Excavator', 'Available'),
            ('EQX1233', 'Excavator', 'Available'),
            ('EQX1234', 'Excavator', 'Available'),
            ('EQX1235', 'Excavator', 'Available'),
            ('EQX1236', 'Excavator', 'Available'),
            ('EQX1237', 'Excavator', 'Available'),
            ('EQX1238', 'Excavator', 'Available'),
            ('EQX1239', 'Excavator', 'Available'),
            ('EQX1240', 'Excavator', 'Available'),
            ('EQX1241', 'Excavator', 'Available'),
            ('EQX1242', 'Excavator', 'Available'),
            ('EQX1243', 'Excavator', 'Available'),
            ('EQX1244', 'Excavator', 'Available'),
            ('EQX1245', 'Excavator', 'Available'),
            ('EQX1246', 'Excavator', 'Available'),
            ('EQX1247', 'Excavator', 'Available'),
            ('EQX1248', 'Excavator', 'Available'),
            ('EQX1249', 'Excavator', 'Available'),
            ('EQX1250', 'Excavator', 'Available'),
            ('EQX1251', 'Crane', 'Available'),
            ('EQX1252', 'Crane', 'Available'),
            ('EQX1253', 'Crane', 'Available'),
            ('EQX1254', 'Crane', 'Available'),
            ('EQX1255', 'Crane', 'Available'),
            ('EQX1256', 'Crane', 'Available'),
            ('EQX1257', 'Crane', 'Available'),
            ('EQX1258', 'Crane', 'Available'),
            ('EQX1259', 'Crane', 'Available'),
            ('EQX1260', 'Crane', 'Available'),
            ('EQX1261', 'Crane', 'Available'),
            ('EQX1262', 'Crane', 'Available'),
            ('EQX1263', 'Crane', 'Available'),
            ('EQX1264', 'Crane', 'Available'),
            ('EQX1265', 'Crane', 'Available'),
            ('EQX1266', 'Crane', 'Available'),
            ('EQX1267', 'Crane', 'Available'),
            ('EQX1268', 'Crane', 'Available'),
            ('EQX1269', 'Crane', 'Available'),
            ('EQX1270', 'Crane', 'Available'),
            ('EQX1271', 'Crane', 'Available'),
            ('EQX1272', 'Crane', 'Available'),
            ('EQX1273', 'Crane', 'Available'),
            ('EQX1274', 'Crane', 'Available'),
            ('EQX1275', 'Crane', 'Available'),
            ('EQX1276', 'Crane', 'Available'),
            ('EQX1277', 'Crane', 'Available'),
            ('EQX1278', 'Crane', 'Available'),
            ('EQX1279', 'Crane', 'Available'),
            ('EQX1280', 'Crane', 'Available'),
            ('EQX1281', 'Crane', 'Available'),
            ('EQX1282', 'Crane', 'Available'),
            ('EQX1283', 'Crane', 'Available'),
            ('EQX1284', 'Crane', 'Available'),
            ('EQX1285', 'Crane', 'Available'),
            ('EQX1286', 'Crane', 'Available'),
            ('EQX1287', 'Crane', 'Available'),
            ('EQX1288', 'Crane', 'Available'),
            ('EQX1289', 'Crane', 'Available'),
            ('EQX1290', 'Crane', 'Available'),
            ('EQX1291', 'Crane', 'Available'),
            ('EQX1292', 'Crane', 'Available'),
            ('EQX1293', 'Crane', 'Available'),
            ('EQX1294', 'Crane', 'Available'),
            ('EQX1295', 'Crane', 'Available'),
            ('EQX1296', 'Crane', 'Available'),
            ('EQX1297', 'Crane', 'Available'),
            ('EQX1298', 'Crane', 'Available'),
            ('EQX1299', 'Crane', 'Available'),
            ('EQX1300', 'Crane', 'Available'),
            ('EQX1301', 'Crane', 'Available'),
            ('EQX1302', 'Crane', 'Available'),
            ('EQX1303', 'Crane', 'Available'),
            ('EQX1304', 'Crane', 'Available'),
            ('EQX1305', 'Crane', 'Available'),
            ('EQX1306', 'Crane', 'Available'),
            ('EQX1307', 'Crane', 'Available'),
            ('EQX1308', 'Crane', 'Available'),
            ('EQX1309', 'Crane', 'Available'),
            ('EQX1310', 'Crane', 'Available'),
            ('EQX1311', 'Crane', 'Available'),
            ('EQX1312', 'Crane', 'Available'),
            ('EQX1313', 'Crane', 'Available'),
            ('EQX1314', 'Crane', 'Available'),
            ('EQX1315', 'Crane', 'Available'),
            ('EQX1316', 'Crane', 'Available'),
            ('EQX1317', 'Crane', 'Available'),
            ('EQX1318', 'Crane', 'Available'),
            ('EQX1319', 'Crane', 'Available'),
            ('EQX1320', 'Crane', 'Available'),
            ('EQX1321', 'Crane', 'Available'),
            ('EQX1322', 'Crane', 'Available'),
            ('EQX1323', 'Crane', 'Available'),
            ('EQX1324', 'Crane', 'Available'),
            ('EQX1325', 'Crane', 'Available'),
            ('EQX1326', 'Crane', 'Available'),
            ('EQX1327', 'Crane', 'Available'),
            ('EQX1328', 'Crane', 'Available'),
            ('EQX1329', 'Crane', 'Available'),
            ('EQX1330', 'Crane', 'Available'),
            ('EQX1331', 'Crane', 'Available'),
            ('EQX1332', 'Crane', 'Available'),
            ('EQX1333', 'Crane', 'Available'),
            ('EQX1334', 'Crane', 'Available'),
            ('EQX1335', 'Crane', 'Available'),
            ('EQX1336', 'Crane', 'Available'),
            ('EQX1337', 'Crane', 'Available'),
            ('EQX1338', 'Crane', 'Available'),
            ('EQX1339', 'Crane', 'Available'),
            ('EQX1340', 'Crane', 'Available'),
            ('EQX1341', 'Crane', 'Available'),
            ('EQX1342', 'Crane', 'Available'),
            ('EQX1343', 'Crane', 'Available'),
            ('EQX1344', 'Crane', 'Available'),
            ('EQX1345', 'Crane', 'Available'),
            ('EQX1346', 'Crane', 'Available'),
            ('EQX1347', 'Crane', 'Available'),
            ('EQX1348', 'Crane', 'Available'),
            ('EQX1349', 'Crane', 'Available'),
            ('EQX1350', 'Crane', 'Available'),
            ('EQX1351', 'Crane', 'Available'),
            ('EQX1352', 'Crane', 'Available'),
            ('EQX1353', 'Crane', 'Available'),
            ('EQX1354', 'Crane', 'Available'),
            ('EQX1355', 'Crane', 'Available'),
            ('EQX1356', 'Crane', 'Available'),
            ('EQX1357', 'Crane', 'Available'),
            ('EQX1358', 'Crane', 'Available'),
            ('EQX1359', 'Crane', 'Available'),
            ('EQX1360', 'Crane', 'Available'),
            ('EQX1361', 'Crane', 'Available'),
            ('EQX1362', 'Crane', 'Available'),
            ('EQX1363', 'Crane', 'Available'),
            ('EQX1364', 'Crane', 'Available'),
            ('EQX1365', 'Crane', 'Available'),
            ('EQX1366', 'Crane', 'Available'),
            ('EQX1367', 'Crane', 'Available'),
            ('EQX1368', 'Crane', 'Available'),
            ('EQX1369', 'Crane', 'Available'),
            ('EQX1370', 'Crane', 'Available'),
            ('EQX1371', 'Crane', 'Available'),
            ('EQX1372', 'Crane', 'Available'),
            ('EQX1373', 'Crane', 'Available'),
            ('EQX1374', 'Crane', 'Available'),
            ('EQX1375', 'Crane', 'Available'),
            ('EQX1376', 'Crane', 'Available'),
            ('EQX1377', 'Crane', 'Available'),
            ('EQX1378', 'Crane', 'Available'),
            ('EQX1379', 'Crane', 'Available'),
            ('EQX1380', 'Crane', 'Available'),
            ('EQX1381', 'Crane', 'Available'),
            ('EQX1382', 'Crane', 'Available'),
            ('EQX1383', 'Crane', 'Available'),
            ('EQX1384', 'Crane', 'Available'),
            ('EQX1385', 'Crane', 'Available'),
            ('EQX1386', 'Crane', 'Available'),
            ('EQX1387', 'Crane', 'Available'),
            ('EQX1388', 'Crane', 'Available'),
            ('EQX1389', 'Crane', 'Available'),
            ('EQX1390', 'Crane', 'Available'),
            ('EQX1391', 'Crane', 'Available'),
            ('EQX1392', 'Crane', 'Available'),
            ('EQX1393', 'Crane', 'Available'),
            ('EQX1394', 'Crane', 'Available'),
            ('EQX1395', 'Crane', 'Available'),
            ('EQX1396', 'Crane', 'Available'),
            ('EQX1397', 'Crane', 'Available'),
            ('EQX1398', 'Crane', 'Available'),
            ('EQX1399', 'Crane', 'Available'),
            ('EQX1400', 'Crane', 'Available'),
            ('EQX1401', 'Crane', 'Available'),
            ('EQX1402', 'Crane', 'Available'),
            ('EQX1403', 'Crane', 'Available'),
            ('EQX1404', 'Crane', 'Available'),
            ('EQX1405', 'Crane', 'Available'),
            ('EQX1406', 'Crane', 'Available'),
            ('EQX1407', 'Crane', 'Available'),
            ('EQX1408', 'Crane', 'Available'),
            ('EQX1409', 'Crane', 'Available'),
            ('EQX1410', 'Crane', 'Available'),
            ('EQX1411', 'Crane', 'Available'),
            ('EQX1412', 'Crane', 'Available'),
            ('EQX1413', 'Crane', 'Available'),
            ('EQX1414', 'Crane', 'Available'),
            ('EQX1415', 'Crane', 'Available'),
            ('EQX1416', 'Crane', 'Available'),
            ('EQX1417', 'Crane', 'Available'),
            ('EQX1418', 'Crane', 'Available'),
            ('EQX1419', 'Crane', 'Available'),
            ('EQX1420', 'Crane', 'Available'),
            ('EQX1421', 'Crane', 'Available'),
            ('EQX1422', 'Crane', 'Available'),
            ('EQX1423', 'Crane', 'Available'),
            ('EQX1424', 'Crane', 'Available'),
            ('EQX1425', 'Crane', 'Available'),
            ('EQX1426', 'Crane', 'Available'),
            ('EQX1427', 'Crane', 'Available'),
            ('EQX1428', 'Crane', 'Available'),
            ('EQX1429', 'Crane', 'Available'),
            ('EQX1430', 'Crane', 'Available'),
            ('EQX1431', 'Crane', 'Available'),
            ('EQX1432', 'Crane', 'Available'),
            ('EQX1433', 'Crane', 'Available'),
            ('EQX1434', 'Crane', 'Available'),
            ('EQX1435', 'Crane', 'Available'),
            ('EQX1436', 'Crane', 'Available'),
            ('EQX1437', 'Crane', 'Available'),
            ('EQX1438', 'Crane', 'Available'),
            ('EQX1439', 'Crane', 'Available'),
            ('EQX1440', 'Crane', 'Available'),
            ('EQX1441', 'Crane', 'Available'),
            ('EQX1442', 'Crane', 'Available'),
            ('EQX1443', 'Crane', 'Available'),
            ('EQX1444', 'Crane', 'Available'),
            ('EQX1445', 'Crane', 'Available'),
            ('EQX1446', 'Crane', 'Available'),
            ('EQX1447', 'Crane', 'Available'),
            ('EQX1448', 'Crane', 'Available'),
            ('EQX1449', 'Crane', 'Available'),
            ('EQX1450', 'Crane', 'Available'),
            ('EQX1451', 'Crane', 'Available'),
            ('EQX1452', 'Crane', 'Available'),
            ('EQX1453', 'Crane', 'Available'),
            ('EQX1454', 'Crane', 'Available'),
            ('EQX1455', 'Crane', 'Available'),
            ('EQX1456', 'Crane', 'Available'),
            ('EQX1457', 'Crane', 'Available'),
            ('EQX1458', 'Crane', 'Available'),
            ('EQX1459', 'Crane', 'Available'),
            ('EQX1460', 'Crane', 'Available'),
            ('EQX1461', 'Crane', 'Available'),
            ('EQX1462', 'Crane', 'Available'),
            ('EQX1463', 'Crane', 'Available'),
            ('EQX1464', 'Crane', 'Available'),
            ('EQX1465', 'Crane', 'Available'),
            ('EQX1466', 'Crane', 'Available'),
            ('EQX1467', 'Crane', 'Available'),
            ('EQX1468', 'Crane', 'Available'),
            ('EQX1469', 'Crane', 'Available'),
            ('EQX1470', 'Crane', 'Available'),
            ('EQX1471', 'Crane', 'Available'),
            ('EQX1472', 'Crane', 'Available'),
            ('EQX1473', 'Crane', 'Available'),
            ('EQX1474', 'Crane', 'Available'),
            ('EQX1475', 'Crane', 'Available'),
            ('EQX1476', 'Crane', 'Available'),
            ('EQX1477', 'Crane', 'Available'),
            ('EQX1478', 'Crane', 'Available'),
            ('EQX1479', 'Crane', 'Available'),
            ('EQX1480', 'Crane', 'Available'),
            ('EQX1481', 'Crane', 'Available'),
            ('EQX1482', 'Crane', 'Available'),
            ('EQX1483', 'Crane', 'Available'),
            ('EQX1484', 'Crane', 'Available'),
            ('EQX1485', 'Crane', 'Available'),
            ('EQX1486', 'Crane', 'Available'),
            ('EQX1487', 'Crane', 'Available'),
            ('EQX1488', 'Crane', 'Available'),
            ('EQX1489', 'Crane', 'Available'),
            ('EQX1490', 'Crane', 'Available'),
            ('EQX1491', 'Crane', 'Available'),
            ('EQX1492', 'Crane', 'Available'),
            ('EQX1493', 'Crane', 'Available'),
            ('EQX1494', 'Crane', 'Available'),
            ('EQX1495', 'Crane', 'Available'),
            ('EQX1496', 'Crane', 'Available'),
            ('EQX1497', 'Crane', 'Available'),
            ('EQX1498', 'Crane', 'Available'),
            ('EQX1499', 'Crane', 'Available'),
            ('EQX1500', 'Crane', 'Available'),
            ('EQX1501', 'Bulldozer', 'Available'),
            ('EQX1502', 'Bulldozer', 'Available'),
            ('EQX1503', 'Bulldozer', 'Available'),
            ('EQX1504', 'Bulldozer', 'Available'),
            ('EQX1505', 'Bulldozer', 'Available'),
            ('EQX1506', 'Bulldozer', 'Available'),
            ('EQX1507', 'Bulldozer', 'Available'),
            ('EQX1508', 'Bulldozer', 'Available'),
            ('EQX1509', 'Bulldozer', 'Available'),
            ('EQX1510', 'Bulldozer', 'Available'),
            ('EQX1511', 'Bulldozer', 'Available'),
            ('EQX1512', 'Bulldozer', 'Available'),
            ('EQX1513', 'Bulldozer', 'Available'),
            ('EQX1514', 'Bulldozer', 'Available'),
            ('EQX1515', 'Bulldozer', 'Available'),
            ('EQX1516', 'Bulldozer', 'Available'),
            ('EQX1517', 'Bulldozer', 'Available'),
            ('EQX1518', 'Bulldozer', 'Available'),
            ('EQX1519', 'Bulldozer', 'Available'),
            ('EQX1520', 'Bulldozer', 'Available'),
            ('EQX1521', 'Bulldozer', 'Available'),
            ('EQX1522', 'Bulldozer', 'Available'),
            ('EQX1523', 'Bulldozer', 'Available'),
            ('EQX1524', 'Bulldozer', 'Available'),
            ('EQX1525', 'Bulldozer', 'Available'),
            ('EQX1526', 'Bulldozer', 'Available'),
            ('EQX1527', 'Bulldozer', 'Available'),
            ('EQX1528', 'Bulldozer', 'Available'),
            ('EQX1529', 'Bulldozer', 'Available'),
            ('EQX1530', 'Bulldozer', 'Available'),
            ('EQX1531', 'Bulldozer', 'Available'),
            ('EQX1532', 'Bulldozer', 'Available'),
            ('EQX1533', 'Bulldozer', 'Available'),
            ('EQX1534', 'Bulldozer', 'Available'),
            ('EQX1535', 'Bulldozer', 'Available'),
            ('EQX1536', 'Bulldozer', 'Available'),
            ('EQX1537', 'Bulldozer', 'Available'),
            ('EQX1538', 'Bulldozer', 'Available'),
            ('EQX1539', 'Bulldozer', 'Available'),
            ('EQX1540', 'Bulldozer', 'Available'),
            ('EQX1541', 'Bulldozer', 'Available'),
            ('EQX1542', 'Bulldozer', 'Available'),
            ('EQX1543', 'Bulldozer', 'Available'),
            ('EQX1544', 'Bulldozer', 'Available'),
            ('EQX1545', 'Bulldozer', 'Available'),
            ('EQX1546', 'Bulldozer', 'Available'),
            ('EQX1547', 'Bulldozer', 'Available'),
            ('EQX1548', 'Bulldozer', 'Available'),
            ('EQX1549', 'Bulldozer', 'Available'),
            ('EQX1550', 'Bulldozer', 'Available'),
            ('EQX1551', 'Bulldozer', 'Available'),
            ('EQX1552', 'Bulldozer', 'Available'),
            ('EQX1553', 'Bulldozer', 'Available'),
            ('EQX1554', 'Bulldozer', 'Available'),
            ('EQX1555', 'Bulldozer', 'Available'),
            ('EQX1556', 'Bulldozer', 'Available'),
            ('EQX1557', 'Bulldozer', 'Available'),
            ('EQX1558', 'Bulldozer', 'Available'),
            ('EQX1559', 'Bulldozer', 'Available'),
            ('EQX1560', 'Bulldozer', 'Available'),
            ('EQX1561', 'Bulldozer', 'Available'),
            ('EQX1562', 'Bulldozer', 'Available'),
            ('EQX1563', 'Bulldozer', 'Available'),
            ('EQX1564', 'Bulldozer', 'Available'),
            ('EQX1565', 'Bulldozer', 'Available'),
            ('EQX1566', 'Bulldozer', 'Available'),
            ('EQX1567', 'Bulldozer', 'Available'),
            ('EQX1568', 'Bulldozer', 'Available'),
            ('EQX1569', 'Bulldozer', 'Available'),
            ('EQX1570', 'Bulldozer', 'Available'),
            ('EQX1571', 'Bulldozer', 'Available'),
            ('EQX1572', 'Bulldozer', 'Available'),
            ('EQX1573', 'Bulldozer', 'Available'),
            ('EQX1574', 'Bulldozer', 'Available'),
            ('EQX1575', 'Bulldozer', 'Available'),
            ('EQX1576', 'Bulldozer', 'Available'),
            ('EQX1577', 'Bulldozer', 'Available'),
            ('EQX1578', 'Bulldozer', 'Available'),
            ('EQX1579', 'Bulldozer', 'Available'),
            ('EQX1580', 'Bulldozer', 'Available'),
            ('EQX1581', 'Bulldozer', 'Available'),
            ('EQX1582', 'Bulldozer', 'Available'),
            ('EQX1583', 'Bulldozer', 'Available'),
            ('EQX1584', 'Bulldozer', 'Available'),
            ('EQX1585', 'Bulldozer', 'Available'),
            ('EQX1586', 'Bulldozer', 'Available'),
            ('EQX1587', 'Bulldozer', 'Available'),
            ('EQX1588', 'Bulldozer', 'Available'),
            ('EQX1589', 'Bulldozer', 'Available'),
            ('EQX1590', 'Bulldozer', 'Available'),
            ('EQX1591', 'Bulldozer', 'Available'),
            ('EQX1592', 'Bulldozer', 'Available'),
            ('EQX1593', 'Bulldozer', 'Available'),
            ('EQX1594', 'Bulldozer', 'Available'),
            ('EQX1595', 'Bulldozer', 'Available'),
            ('EQX1596', 'Bulldozer', 'Available'),
            ('EQX1597', 'Bulldozer', 'Available'),
            ('EQX1598', 'Bulldozer', 'Available'),
            ('EQX1599', 'Bulldozer', 'Available'),
            ('EQX1600', 'Bulldozer', 'Available'),
            ('EQX1601', 'Bulldozer', 'Available'),
            ('EQX1602', 'Bulldozer', 'Available'),
            ('EQX1603', 'Bulldozer', 'Available'),
            ('EQX1604', 'Bulldozer', 'Available'),
            ('EQX1605', 'Bulldozer', 'Available'),
            ('EQX1606', 'Bulldozer', 'Available'),
            ('EQX1607', 'Bulldozer', 'Available'),
            ('EQX1608', 'Bulldozer', 'Available'),
            ('EQX1609', 'Bulldozer', 'Available'),
            ('EQX1610', 'Bulldozer', 'Available'),
            ('EQX1611', 'Bulldozer', 'Available'),
            ('EQX1612', 'Bulldozer', 'Available'),
            ('EQX1613', 'Bulldozer', 'Available'),
            ('EQX1614', 'Bulldozer', 'Available'),
            ('EQX1615', 'Bulldozer', 'Available'),
            ('EQX1616', 'Bulldozer', 'Available'),
            ('EQX1617', 'Bulldozer', 'Available'),
            ('EQX1618', 'Bulldozer', 'Available'),
            ('EQX1619', 'Bulldozer', 'Available'),
            ('EQX1620', 'Bulldozer', 'Available'),
            ('EQX1621', 'Bulldozer', 'Available'),
            ('EQX1622', 'Bulldozer', 'Available'),
            ('EQX1623', 'Bulldozer', 'Available'),
            ('EQX1624', 'Bulldozer', 'Available'),
            ('EQX1625', 'Bulldozer', 'Available'),
            ('EQX1626', 'Bulldozer', 'Available'),
            ('EQX1627', 'Bulldozer', 'Available'),
            ('EQX1628', 'Bulldozer', 'Available'),
            ('EQX1629', 'Bulldozer', 'Available'),
            ('EQX1630', 'Bulldozer', 'Available'),
            ('EQX1631', 'Bulldozer', 'Available'),
            ('EQX1632', 'Bulldozer', 'Available'),
            ('EQX1633', 'Bulldozer', 'Available'),
            ('EQX1634', 'Bulldozer', 'Available'),
            ('EQX1635', 'Bulldozer', 'Available'),
            ('EQX1636', 'Bulldozer', 'Available'),
            ('EQX1637', 'Bulldozer', 'Available'),
            ('EQX1638', 'Bulldozer', 'Available'),
            ('EQX1639', 'Bulldozer', 'Available'),
            ('EQX1640', 'Bulldozer', 'Available'),
            ('EQX1641', 'Bulldozer', 'Available'),
            ('EQX1642', 'Bulldozer', 'Available'),
            ('EQX1643', 'Bulldozer', 'Available'),
            ('EQX1644', 'Bulldozer', 'Available'),
            ('EQX1645', 'Bulldozer', 'Available'),
            ('EQX1646', 'Bulldozer', 'Available'),
            ('EQX1647', 'Bulldozer', 'Available'),
            ('EQX1648', 'Bulldozer', 'Available'),
            ('EQX1649', 'Bulldozer', 'Available'),
            ('EQX1650', 'Bulldozer', 'Available'),
            ('EQX1651', 'Bulldozer', 'Available'),
            ('EQX1652', 'Bulldozer', 'Available'),
            ('EQX1653', 'Bulldozer', 'Available'),
            ('EQX1654', 'Bulldozer', 'Available'),
            ('EQX1655', 'Bulldozer', 'Available'),
            ('EQX1656', 'Bulldozer', 'Available'),
            ('EQX1657', 'Bulldozer', 'Available'),
            ('EQX1658', 'Bulldozer', 'Available'),
            ('EQX1659', 'Bulldozer', 'Available'),
            ('EQX1660', 'Bulldozer', 'Available'),
            ('EQX1661', 'Bulldozer', 'Available'),
            ('EQX1662', 'Bulldozer', 'Available'),
            ('EQX1663', 'Bulldozer', 'Available'),
            ('EQX1664', 'Bulldozer', 'Available'),
            ('EQX1665', 'Bulldozer', 'Available'),
            ('EQX1666', 'Bulldozer', 'Available'),
            ('EQX1667', 'Bulldozer', 'Available'),
            ('EQX1668', 'Bulldozer', 'Available'),
            ('EQX1669', 'Bulldozer', 'Available'),
            ('EQX1670', 'Bulldozer', 'Available'),
            ('EQX1671', 'Bulldozer', 'Available'),
            ('EQX1672', 'Bulldozer', 'Available'),
            ('EQX1673', 'Bulldozer', 'Available'),
            ('EQX1674', 'Bulldozer', 'Available'),
            ('EQX1675', 'Bulldozer', 'Available'),
            ('EQX1676', 'Bulldozer', 'Available'),
            ('EQX1677', 'Bulldozer', 'Available'),
            ('EQX1678', 'Bulldozer', 'Available'),
            ('EQX1679', 'Bulldozer', 'Available'),
            ('EQX1680', 'Bulldozer', 'Available'),
            ('EQX1681', 'Bulldozer', 'Available'),
            ('EQX1682', 'Bulldozer', 'Available'),
            ('EQX1683', 'Bulldozer', 'Available'),
            ('EQX1684', 'Bulldozer', 'Available'),
            ('EQX1685', 'Bulldozer', 'Available'),
            ('EQX1686', 'Bulldozer', 'Available'),
            ('EQX1687', 'Bulldozer', 'Available'),
            ('EQX1688', 'Bulldozer', 'Available'),
            ('EQX1689', 'Bulldozer', 'Available'),
            ('EQX1690', 'Bulldozer', 'Available'),
            ('EQX1691', 'Bulldozer', 'Available'),
            ('EQX1692', 'Bulldozer', 'Available'),
            ('EQX1693', 'Bulldozer', 'Available'),
            ('EQX1694', 'Bulldozer', 'Available'),
            ('EQX1695', 'Bulldozer', 'Available'),
            ('EQX1696', 'Bulldozer', 'Available'),
            ('EQX1697', 'Bulldozer', 'Available'),
            ('EQX1698', 'Bulldozer', 'Available'),
            ('EQX1699', 'Bulldozer', 'Available'),
            ('EQX1700', 'Bulldozer', 'Available'),
            ('EQX1701', 'Bulldozer', 'Available'),
            ('EQX1702', 'Bulldozer', 'Available'),
            ('EQX1703', 'Bulldozer', 'Available'),
            ('EQX1704', 'Bulldozer', 'Available'),
            ('EQX1705', 'Bulldozer', 'Available'),
            ('EQX1706', 'Bulldozer', 'Available'),
            ('EQX1707', 'Bulldozer', 'Available'),
            ('EQX1708', 'Bulldozer', 'Available'),
            ('EQX1709', 'Bulldozer', 'Available'),
            ('EQX1710', 'Bulldozer', 'Available'),
            ('EQX1711', 'Bulldozer', 'Available'),
            ('EQX1712', 'Bulldozer', 'Available'),
            ('EQX1713', 'Bulldozer', 'Available'),
            ('EQX1714', 'Bulldozer', 'Available'),
            ('EQX1715', 'Bulldozer', 'Available'),
            ('EQX1716', 'Bulldozer', 'Available'),
            ('EQX1717', 'Bulldozer', 'Available'),
            ('EQX1718', 'Bulldozer', 'Available'),
            ('EQX1719', 'Bulldozer', 'Available'),
            ('EQX1720', 'Bulldozer', 'Available'),
            ('EQX1721', 'Bulldozer', 'Available'),
            ('EQX1722', 'Bulldozer', 'Available'),
            ('EQX1723', 'Bulldozer', 'Available'),
            ('EQX1724', 'Bulldozer', 'Available'),
            ('EQX1725', 'Bulldozer', 'Available'),
            ('EQX1726', 'Bulldozer', 'Available'),
            ('EQX1727', 'Bulldozer', 'Available'),
            ('EQX1728', 'Bulldozer', 'Available'),
            ('EQX1729', 'Bulldozer', 'Available'),
            ('EQX1730', 'Bulldozer', 'Available'),
            ('EQX1731', 'Bulldozer', 'Available'),
            ('EQX1732', 'Bulldozer', 'Available'),
            ('EQX1733', 'Bulldozer', 'Available'),
            ('EQX1734', 'Bulldozer', 'Available'),
            ('EQX1735', 'Bulldozer', 'Available'),
            ('EQX1736', 'Bulldozer', 'Available'),
            ('EQX1737', 'Bulldozer', 'Available'),
            ('EQX1738', 'Bulldozer', 'Available'),
            ('EQX1739', 'Bulldozer', 'Available'),
            ('EQX1740', 'Bulldozer', 'Available'),
            ('EQX1741', 'Bulldozer', 'Available'),
            ('EQX1742', 'Bulldozer', 'Available'),
            ('EQX1743', 'Bulldozer', 'Available'),
            ('EQX1744', 'Bulldozer', 'Available'),
            ('EQX1745', 'Bulldozer', 'Available'),
            ('EQX1746', 'Bulldozer', 'Available'),
            ('EQX1747', 'Bulldozer', 'Available'),
            ('EQX1748', 'Bulldozer', 'Available'),
            ('EQX1749', 'Bulldozer', 'Available'),
            ('EQX1750', 'Bulldozer', 'Available'),
            ('EQX1751', 'Grader', 'Available'),
            ('EQX1752', 'Grader', 'Available'),
            ('EQX1753', 'Grader', 'Available'),
            ('EQX1754', 'Grader', 'Available'),
            ('EQX1755', 'Grader', 'Available'),
            ('EQX1756', 'Grader', 'Available'),
            ('EQX1757', 'Grader', 'Available'),
            ('EQX1758', 'Grader', 'Available'),
            ('EQX1759', 'Grader', 'Available'),
            ('EQX1760', 'Grader', 'Available'),
            ('EQX1761', 'Grader', 'Available'),
            ('EQX1762', 'Grader', 'Available'),
            ('EQX1763', 'Grader', 'Available'),
            ('EQX1764', 'Grader', 'Available'),
            ('EQX1765', 'Grader', 'Available'),
            ('EQX1766', 'Grader', 'Available'),
            ('EQX1767', 'Grader', 'Available'),
            ('EQX1768', 'Grader', 'Available'),
            ('EQX1769', 'Grader', 'Available'),
            ('EQX1770', 'Grader', 'Available'),
            ('EQX1771', 'Grader', 'Available'),
            ('EQX1772', 'Grader', 'Available'),
            ('EQX1773', 'Grader', 'Available'),
            ('EQX1774', 'Grader', 'Available'),
            ('EQX1775', 'Grader', 'Available'),
            ('EQX1776', 'Grader', 'Available'),
            ('EQX1777', 'Grader', 'Available'),
            ('EQX1778', 'Grader', 'Available'),
            ('EQX1779', 'Grader', 'Available'),
            ('EQX1780', 'Grader', 'Available'),
            ('EQX1781', 'Grader', 'Available'),
            ('EQX1782', 'Grader', 'Available'),
            ('EQX1783', 'Grader', 'Available'),
            ('EQX1784', 'Grader', 'Available'),
            ('EQX1785', 'Grader', 'Available'),
            ('EQX1786', 'Grader', 'Available'),
            ('EQX1787', 'Grader', 'Available'),
            ('EQX1788', 'Grader', 'Available'),
            ('EQX1789', 'Grader', 'Available'),
            ('EQX1790', 'Grader', 'Available'),
            ('EQX1791', 'Grader', 'Available'),
            ('EQX1792', 'Grader', 'Available'),
            ('EQX1793', 'Grader', 'Available'),
            ('EQX1794', 'Grader', 'Available'),
            ('EQX1795', 'Grader', 'Available'),
            ('EQX1796', 'Grader', 'Available'),
            ('EQX1797', 'Grader', 'Available'),
            ('EQX1798', 'Grader', 'Available'),
            ('EQX1799', 'Grader', 'Available'),
            ('EQX1800', 'Grader', 'Available'),
            ('EQX1801', 'Grader', 'Available'),
            ('EQX1802', 'Grader', 'Available'),
            ('EQX1803', 'Grader', 'Available'),
            ('EQX1804', 'Grader', 'Available'),
            ('EQX1805', 'Grader', 'Available'),
            ('EQX1806', 'Grader', 'Available'),
            ('EQX1807', 'Grader', 'Available'),
            ('EQX1808', 'Grader', 'Available'),
            ('EQX1809', 'Grader', 'Available'),
            ('EQX1810', 'Grader', 'Available'),
            ('EQX1811', 'Grader', 'Available'),
            ('EQX1812', 'Grader', 'Available'),
            ('EQX1813', 'Grader', 'Available'),
            ('EQX1814', 'Grader', 'Available'),
            ('EQX1815', 'Grader', 'Available'),
            ('EQX1816', 'Grader', 'Available'),
            ('EQX1817', 'Grader', 'Available'),
            ('EQX1818', 'Grader', 'Available'),
            ('EQX1819', 'Grader', 'Available'),
            ('EQX1820', 'Grader', 'Available'),
            ('EQX1821', 'Grader', 'Available'),
            ('EQX1822', 'Grader', 'Available'),
            ('EQX1823', 'Grader', 'Available'),
            ('EQX1824', 'Grader', 'Available'),
            ('EQX1825', 'Grader', 'Available'),
            ('EQX1826', 'Grader', 'Available'),
            ('EQX1827', 'Grader', 'Available'),
            ('EQX1828', 'Grader', 'Available'),
            ('EQX1829', 'Grader', 'Available'),
            ('EQX1830', 'Grader', 'Available'),
            ('EQX1831', 'Grader', 'Available'),
            ('EQX1832', 'Grader', 'Available'),
            ('EQX1833', 'Grader', 'Available'),
            ('EQX1834', 'Grader', 'Available'),
            ('EQX1835', 'Grader', 'Available'),
            ('EQX1836', 'Grader', 'Available'),
            ('EQX1837', 'Grader', 'Available'),
            ('EQX1838', 'Grader', 'Available'),
            ('EQX1839', 'Grader', 'Available'),
            ('EQX1840', 'Grader', 'Available'),
            ('EQX1841', 'Grader', 'Available'),
            ('EQX1842', 'Grader', 'Available'),
            ('EQX1843', 'Grader', 'Available'),
            ('EQX1844', 'Grader', 'Available'),
            ('EQX1845', 'Grader', 'Available'),
            ('EQX1846', 'Grader', 'Available'),
            ('EQX1847', 'Grader', 'Available'),
            ('EQX1848', 'Grader', 'Available'),
            ('EQX1849', 'Grader', 'Available'),
            ('EQX1850', 'Grader', 'Available'),
            ('EQX1851', 'Grader', 'Available'),
            ('EQX1852', 'Grader', 'Available'),
            ('EQX1853', 'Grader', 'Available'),
            ('EQX1854', 'Grader', 'Available'),
            ('EQX1855', 'Grader', 'Available'),
            ('EQX1856', 'Grader', 'Available'),
            ('EQX1857', 'Grader', 'Available'),
            ('EQX1858', 'Grader', 'Available'),
            ('EQX1859', 'Grader', 'Available'),
            ('EQX1860', 'Grader', 'Available'),
            ('EQX1861', 'Grader', 'Available'),
            ('EQX1862', 'Grader', 'Available'),
            ('EQX1863', 'Grader', 'Available'),
            ('EQX1864', 'Grader', 'Available'),
            ('EQX1865', 'Grader', 'Available'),
            ('EQX1866', 'Grader', 'Available'),
            ('EQX1867', 'Grader', 'Available'),
            ('EQX1868', 'Grader', 'Available'),
            ('EQX1869', 'Grader', 'Available'),
            ('EQX1870', 'Grader', 'Available'),
            ('EQX1871', 'Grader', 'Available'),
            ('EQX1872', 'Grader', 'Available'),
            ('EQX1873', 'Grader', 'Available'),
            ('EQX1874', 'Grader', 'Available'),
            ('EQX1875', 'Grader', 'Available'),
            ('EQX1876', 'Grader', 'Available'),
            ('EQX1877', 'Grader', 'Available'),
            ('EQX1878', 'Grader', 'Available'),
            ('EQX1879', 'Grader', 'Available'),
            ('EQX1880', 'Grader', 'Available'),
            ('EQX1881', 'Grader', 'Available'),
            ('EQX1882', 'Grader', 'Available'),
            ('EQX1883', 'Grader', 'Available'),
            ('EQX1884', 'Grader', 'Available'),
            ('EQX1885', 'Grader', 'Available'),
            ('EQX1886', 'Grader', 'Available'),
            ('EQX1887', 'Grader', 'Available'),
            ('EQX1888', 'Grader', 'Available'),
            ('EQX1889', 'Grader', 'Available'),
            ('EQX1890', 'Grader', 'Available'),
            ('EQX1891', 'Grader', 'Available'),
            ('EQX1892', 'Grader', 'Available'),
            ('EQX1893', 'Grader', 'Available'),
            ('EQX1894', 'Grader', 'Available'),
            ('EQX1895', 'Grader', 'Available'),
            ('EQX1896', 'Grader', 'Available'),
            ('EQX1897', 'Grader', 'Available'),
            ('EQX1898', 'Grader', 'Available'),
            ('EQX1899', 'Grader', 'Available'),
            ('EQX1900', 'Grader', 'Available'),
            ('EQX1901', 'Grader', 'Available'),
            ('EQX1902', 'Grader', 'Available'),
            ('EQX1903', 'Grader', 'Available'),
            ('EQX1904', 'Grader', 'Available'),
            ('EQX1905', 'Grader', 'Available'),
            ('EQX1906', 'Grader', 'Available'),
            ('EQX1907', 'Grader', 'Available'),
            ('EQX1908', 'Grader', 'Available'),
            ('EQX1909', 'Grader', 'Available'),
            ('EQX1910', 'Grader', 'Available'),
            ('EQX1911', 'Grader', 'Available'),
            ('EQX1912', 'Grader', 'Available'),
            ('EQX1913', 'Grader', 'Available'),
            ('EQX1914', 'Grader', 'Available'),
            ('EQX1915', 'Grader', 'Available'),
            ('EQX1916', 'Grader', 'Available'),
            ('EQX1917', 'Grader', 'Available'),
            ('EQX1918', 'Grader', 'Available'),
            ('EQX1919', 'Grader', 'Available'),
            ('EQX1920', 'Grader', 'Available'),
            ('EQX1921', 'Grader', 'Available'),
            ('EQX1922', 'Grader', 'Available'),
            ('EQX1923', 'Grader', 'Available'),
            ('EQX1924', 'Grader', 'Available'),
            ('EQX1925', 'Grader', 'Available'),
            ('EQX1926', 'Grader', 'Available'),
            ('EQX1927', 'Grader', 'Available'),
            ('EQX1928', 'Grader', 'Available'),
            ('EQX1929', 'Grader', 'Available'),
            ('EQX1930', 'Grader', 'Available'),
            ('EQX1931', 'Grader', 'Available'),
            ('EQX1932', 'Grader', 'Available'),
            ('EQX1933', 'Grader', 'Available'),
            ('EQX1934', 'Grader', 'Available'),
            ('EQX1935', 'Grader', 'Available'),
            ('EQX1936', 'Grader', 'Available'),
            ('EQX1937', 'Grader', 'Available'),
            ('EQX1938', 'Grader', 'Available'),
            ('EQX1939', 'Grader', 'Available'),
            ('EQX1940', 'Grader', 'Available'),
            ('EQX1941', 'Grader', 'Available'),
            ('EQX1942', 'Grader', 'Available'),
            ('EQX1943', 'Grader', 'Available'),
            ('EQX1944', 'Grader', 'Available'),
            ('EQX1945', 'Grader', 'Available'),
            ('EQX1946', 'Grader', 'Available'),
            ('EQX1947', 'Grader', 'Available'),
            ('EQX1948', 'Grader', 'Available'),
            ('EQX1949', 'Grader', 'Available'),
            ('EQX1950', 'Grader', 'Available'),
            ('EQX1951', 'Grader', 'Available'),
            ('EQX1952', 'Grader', 'Available'),
            ('EQX1953', 'Grader', 'Available'),
            ('EQX1954', 'Grader', 'Available'),
            ('EQX1955', 'Grader', 'Available'),
            ('EQX1956', 'Grader', 'Available'),
            ('EQX1957', 'Grader', 'Available'),
            ('EQX1958', 'Grader', 'Available'),
            ('EQX1959', 'Grader', 'Available'),
            ('EQX1960', 'Grader', 'Available'),
            ('EQX1961', 'Grader', 'Available'),
            ('EQX1962', 'Grader', 'Available'),
            ('EQX1963', 'Grader', 'Available'),
            ('EQX1964', 'Grader', 'Available'),
            ('EQX1965', 'Grader', 'Available'),
            ('EQX1966', 'Grader', 'Available'),
            ('EQX1967', 'Grader', 'Available'),
            ('EQX1968', 'Grader', 'Available'),
            ('EQX1969', 'Grader', 'Available'),
            ('EQX1970', 'Grader', 'Available'),
            ('EQX1971', 'Grader', 'Available'),
            ('EQX1972', 'Grader', 'Available'),
            ('EQX1973', 'Grader', 'Available'),
            ('EQX1974', 'Grader', 'Available'),
            ('EQX1975', 'Grader', 'Available'),
            ('EQX1976', 'Grader', 'Available'),
            ('EQX1977', 'Grader', 'Available'),
            ('EQX1978', 'Grader', 'Available'),
            ('EQX1979', 'Grader', 'Available'),
            ('EQX1980', 'Grader', 'Available'),
            ('EQX1981', 'Grader', 'Available'),
            ('EQX1982', 'Grader', 'Available'),
            ('EQX1983', 'Grader', 'Available'),
            ('EQX1984', 'Grader', 'Available'),
            ('EQX1985', 'Grader', 'Available'),
            ('EQX1986', 'Grader', 'Available'),
            ('EQX1987', 'Grader', 'Available'),
            ('EQX1988', 'Grader', 'Available'),
            ('EQX1989', 'Grader', 'Available'),
            ('EQX1990', 'Grader', 'Available'),
            ('EQX1991', 'Grader', 'Available'),
            ('EQX1992', 'Grader', 'Available'),
            ('EQX1993', 'Grader', 'Available'),
            ('EQX1994', 'Grader', 'Available'),
            ('EQX1995', 'Grader', 'Available'),
            ('EQX1996', 'Grader', 'Available'),
            ('EQX1997', 'Grader', 'Available'),
            ('EQX1998', 'Grader', 'Available'),
            ('EQX1999', 'Grader', 'Available'),
            ('EQX2000', 'Grader', 'Available')
        ]

        cursor.executemany("""
        INSERT INTO Vendor (EquipmentID, Type, Availability)
        VALUES (?, ?, ?)
        """, equipment_list)

        conn.commit()
        print("✅ Vendor table pre-populated with default equipment data.")

    conn.close()

def insert_site(site_id, location, contact):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("INSERT INTO SiteInfo (SiteID, Location, ContactDetails) VALUES (?, ?, ?)",
                   (site_id, location, contact))
    conn.commit()
    conn.close()

def insert_vendor(type_, site_id, operating_days, location, start_date, rental_type, availability="Available"):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO Vendor (Type, SiteID, OperatingDays, Location, CheckOutDate, Availability, RentalType)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (type_, site_id, operating_days, location, start_date, availability, rental_type))
    conn.commit()
    conn.close()

def fetch_vendors(filter_by=None, site_id=None):
    conn = get_connection()
    cursor = conn.cursor()
    
    query = "SELECT * FROM Vendor WHERE 1=1"
    params = []
    
    if filter_by == "Available":
        query += " AND Availability='Available'"
    elif filter_by == "Rented":
        query += " AND Availability='Rented'"
    
    if site_id:
        query += " AND SiteID=?"
        params.append(site_id)
    
    cursor.execute(query, params)
    rows = cursor.fetchall()
    conn.close()
    return rows

def get_available_types():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT DISTINCT Type
        FROM Vendor
        WHERE Availability = 'Available'
    """)
    types = [row[0] for row in cursor.fetchall()]
    conn.close()
    return types

# Get one available equipmentID for a given type
def get_available_equipment(type_):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT EquipmentID FROM Vendor WHERE Type=? AND Availability='Available' LIMIT 1", (type_,))
    row = cursor.fetchone()
    conn.close()
    return row[0] if row else None

# Update Vendor row when rented
def rent_equipment(equipment_id, site_id, operating_days, location, start_date, rental_type):
    conn = get_connection()
    cursor = conn.cursor()

    # Compute end date and days left
    cursor.execute("SELECT date(?, '+' || ? || ' days')", (start_date, operating_days))
    end_date = cursor.fetchone()[0]

    cursor.execute("SELECT julianday(?) - julianday('now')", (end_date,))
    days_left = int(cursor.fetchone()[0])

    # Update Vendor table (mark rented + add details)
    cursor.execute("""
        UPDATE Vendor
        SET SiteID = ?,
            CheckOutDate = ?,
            CheckInDate = ?,
            OperatingDays = ?,
            DaysLeft = ?,
            Location = ?,
            RentalType = ?,
            Availability = 'Rented'
        WHERE EquipmentID = ?
    """, (site_id, start_date, end_date, operating_days, days_left, location, rental_type, equipment_id))

    conn.commit()
    conn.close()

def get_available_equipment_ids(type_):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT EquipmentID
        FROM Vendor
        WHERE Type = ? AND Availability = 'Available'
    """, (type_,))
    ids = [row[0] for row in cursor.fetchall()]
    conn.close()
    return ids

# Update usage (engine + idle hours) for rented equipment
def update_usage(equipment_id, engine_hours, idle_hours):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        UPDATE Vendor
        SET EngineHourDay = COALESCE(EngineHourDay, 0) + ?,
            IdleHourDay   = COALESCE(IdleHourDay, 0) + ?
        WHERE EquipmentID = ? AND Availability = 'Rented'
    """, (engine_hours, idle_hours, equipment_id))
    conn.commit()
    conn.close()

import time
import random

def simulate_realtime_updates():
    rented_ids = fetch_vendors(filter_by="Rented")  # Get rented equipment
    equipment_ids = [row[0] for row in rented_ids]  # First column is EquipmentID
    
    while True:
        if equipment_ids:
            # Pick a random rented equipment
            eq_id = random.choice(equipment_ids)
            
            # Fake sensor data (hours used in last interval)
            engine_hours = round(random.uniform(0.1, 1.0), 2)
            idle_hours   = round(random.uniform(0.0, 0.5), 2)

            update_usage(eq_id, engine_hours, idle_hours)
            print(f"Updated {eq_id}: +{engine_hours} engine hr, +{idle_hours} idle hr")

        time.sleep(2)  # wait 2 sec like real-time stream

def update_fuel(equipment_id, fuel):
    from database.db import get_connection
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        UPDATE Vendor
        SET Fuel = ?
        WHERE EquipmentID = ? AND Availability = 'Rented'
    """, (fuel, equipment_id))
    conn.commit()
    conn.close()